### DISCUSSION TITLE
Expired Published Certificates

### DISCUSSION THREAD

**Discussion by shift-f10** [pyrou/traefik.me#13] [General]
Hello, first of all this service is amazing. There is an issue today with the published certificates on the site. They have expired as of today and the latest ones have not been pushed it seems.  I have downloaded the latest one on the site today and the output is as follows:

EnhancedKeyUsageList : {Server Authentication (1.3.6.1.5.5.7.3.1), Client Authentication (1.3.6.1.5.5.7.3.2)}
DnsNameList          : {*.traefik.me, traefik.me}
SendAsTrustedIssuer  : False
Archived             : False
Extensions           : {System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid...}
FriendlyName         :
IssuerName           : System.Security.Cryptography.X509Certificates.X500DistinguishedName
NotAfter             : 3/7/2025 4:48:14 AM
NotBefore            : 12/7/2024 4:48:15 AM
HasPrivateKey        : False
PrivateKey           :
PublicKey            : System.Security.Cryptography.X509Certificates.PublicKey
RawData              : {48, 130, 3, 131...}
SerialNumber         : 03DF2E998AADB3AF139D8A13A339347E804C
SubjectName          : System.Security.Cryptography.X509Certificates.X500DistinguishedName
SignatureAlgorithm   : System.Security.Cryptography.Oid
Thumbprint           : 8A2612A28DCB752E4618526323AB27105BC65B59
Version              : 3
Handle               : 2334239328320
Issuer               : CN=E5, O=Let's Encrypt, C=US
Subject              : CN=traefik.me

Seems either the automatic process to publish the certs is broken or not working as intended.

**Comment by joaquinjsb** [comment]
Came here for this too

**Comment by creechy** [comment]
Help @pyrou  ! :-)

**Comment by 1hachem** [comment]
😭

**Comment by creechy** [comment]
Looks like its happened before - https://gist.github.com/pyrou/4f555cd55677331c742742ee6007a73a?permalink_comment_id=4481302#gistcomment-4481302

Hope @pyrou can take a look soon!

**Comment by 1hachem** [comment]
I just had to setup my own domain name, point it to localhost, and get a wild card certificate following dns challenge setup for my provider with traefik 

```
  traefik:
    image: traefik:v3.3.4
    container_name: proxy
    restart: unless-stopped
    networks:
      - proxy_net
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    environment:
      - DO_AUTH_TOKEN=${DO_AUTH_TOKEN}
    command:
      - --log.level=INFO
      - --global.sendAnonymousUsage=false
      - --api.insecure=true

      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https

      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=digitalocean

      - --certificatesresolvers.letsencrypt.acme.email=youremail@email.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json

      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certresolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=domain.com
      - --entryPoints.websecure.http.tls.domains[0].sans=*.domain.com

```
